# Site wide configuration

title: 童心向上的小站
description: "不断学习，一直学习，哈哈"
logo: 120x120.gif # 120x120 px default image used for Twitter summary card
teaser: 400x250.gif # 400x250 px default teaser image used in image archive grid
locale: zh_CN
url:  

# Jekyll configuration
 
sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
# 每一页显示的文章数
paginate: 5  
gems:
  - jekyll-sitemap


  
# Site owner
owner:
  name: txxs
  web: http://locere.com
  email: sdlyjhm01@sina.com
  twitter: 
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: aicdgh5canvas


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
